# Site settings
title:       Romance Office
email:       info@romanceoffice.com
address:     Zollstrasse 121
zip:         8005
city:        Zurich
country:     Switzerland
telephone:   +41 79 316 8600
description: Transmedia Studio found by Creative Director Asher Caplan
copyright:   Romance Office
twitter:
baseurl:     ""
url:         "https://romanceoffice.com"
version:     2.4.0

# Build settings
markdown:    kramdown
kramdown:
 input:      GFM
 hard_wrap:  false
permalink:   /:categories/:title/

exclude:
 - Gemfile
 - Gemfile.lock
 - LICENSEÃŸ
 - gulpfile.js
 - package.json
 - package-lock.json
 - DS_Store
 - Icon
 - node_modules
 - .workinprogress

github:      officeromance
instagram:   romanceoffice
google:
 plus:       +accaplan
 analytics:  UA-74264050-1
 verify:     Rt71Q1qGvbUviohh6n8KmtRoGUd-XeuuuKLBjCMvHO8

# instuff
userId:      '1568291819'
clientId:    '387d80cc65e1414198434cac0666c7d0'
accessToken: '1568291819.387d80c.54f7945b8fd9410a9966d9d79f7f7762'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
